# Generated by Django 4.0.3 on 2022-03-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country_code', models.CharField(choices=[('CZ', 'Cz'), ('UK', 'Uk'), ('SK', 'Sk')], max_length=2)),
                ('last_update_dt', models.DateTimeField(auto_now_add=True)),
                ('average_temperature', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'country_code')},
            },
        ),
    ]
