# Generated by Django 4.0.3 on 2022-03-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyforecast',
            name='last_update_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
